name: Twitter Project CI

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8-oracle
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: twitter-client
          MYSQL_PASSWORD: twitter-password
          MYSQL_DATABASE: twitter
        ports:
          - 3306:3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql-test:
        image: mysql:8-oracle
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: test-user
          MYSQL_PASSWORD: test-password
          MYSQL_DATABASE: twitter-test
        ports:
          - 3307:3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Build with Maven
        working-directory: ./twitter
        run: mvn -B clean test package --file pom.xml

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ./twitter
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vitalie7bocicov_FiiPractic-Twitter
